FROM registry.acess.redhat.com/ubi8/ubi:8.0

MAINTAINER Red Hat Taining <training@redhat.com>

ENV JAVA_OPTIONS -Xmx512m

RUN yum install -y --disableplugin=subscription-manager java-1.8.0-openjdk-headless && \
yum clean all --disableplugiin=subscription-manager -y && \
mkdir -p /opt/app-root/bin

ADD https://github.com/RedHatTrainig/DO288-apps/releases/download/OCP-4.1-1/hello-java.jar /opt/app-root/bin/

COPY run-app.sh /opt/app-root/bin/

RUN chgrp -R 0 /opt/app-root && \
chmod -R g=u /opt/app-root

EXPOSE 8080

USER 1001

CMD /opt/app-root/bin/run-app.sh
